#!/bin/bash


h=$(hostname)
ver=T
pVer=S
t=$1
d=${2:-0}

if [[ $t == "" ]]; then
 echo "Usage: getNeighbors [commit|tree|blob|a|p|P|f] depth object";
 exit 1;
fi

perl /home/audris/lookup/getNeighbors.perl $1 $2 $3 

