#!/bin/bash

h=$(hostname)
ver=S
pVer=R
flat=n
pass=""
while getopts "fv:" option
do 
 case $option in
 f) flat=y; pass="$pass -f" ;;
 v) ver=$OPTARG; pass="$pass -v$ver";; esac
done
shift $((OPTIND-1))
t=$1

if [[ $t == "" ]]; then
 echo "Usage: getValue [OPTIONS] map";
 exit 1;
fi

#determine the fastest database
ssh=""
if [[ -f /fast/${t}Full$ver.31.tch ]]
then path=/fast/${t}Full$ver
else
  if [[ -f /fast/${t}Full$pVer.31.tch ]]
  then ver=$pVer
       path=/fast/${t}Full$ver
  else
    if [[ -f /data/basemaps/${t}Full$ver.31.tch ]]
    then path=/data/basemaps/${t}Full$ver
    else
      if [[ -f /data/basemaps/${t}Full$pVer.31.tch ]]
      then ver=$pVer
        path=/data/basemaps/${t}Full$ver
      else
        path=$(ls -f /da?_data/basemaps/${t}Full$ver.31.tch 2> /dev/null)
        if [[ -f $path ]]
        then
          path=$(ls -f /da?_data/basemaps/${t}Full$ver.31.tch)
          path=${path%%.31.tch}
          ssh=${path%%_data*}
          ssh="ssh "${ssh##/}
        else
          ver=$pVer
          path=$(ls -f /da?_data/basemaps/${t}Full$ver.31.tch)
          path=${path%%.31.tch}
          ssh=${path%%_data*}
          ssh="ssh "${ssh##/}
        fi
      fi
    fi
  fi
fi

if [[ $h == 'da5.eecs.utk.edu' ]] 
then 
  [[ -f /fast/${t}Full$ver.31.tch ]] || ([[ -f /fast/${t}Full$pVer.31.tch ]] && ver=$pVer)
  ~/lookup/getValues.perl --flat=$flat /fast/${t}Full$ver
else
  if [[ $ssh != "" ]] 
  then $ssh "~/lookup/getValues.perl --flat=$flat $path"
  else ~/lookup/getValues.perl --flat=$flat $path
  fi
fi
