#!/bin/bash

h=$(hostname)
ver=P
flat=n
pass=""
while getopts "fv:" option
do 
 case $option in
 f) flat=y; pass="$pass -f" ;;
 v) ver=$OPTARG; pass="$pass -v$ver";; esac
done
shift $((OPTIND-1))
t=$1

declare -A da3
for i in a2b a2c a2f a2p b2a b2f c2b c2f c2p c2ta f2c p2a p2c c2cc c2pc c2h c2r
do da3[$i]=1
done

if [[ $h == da5.eecs.utk.edu ]] 
then 
  [[ -f /fast/${t}Full$ver.0.tch ]] || ([[ /fast/${t}FullQ.0.tch ]] && ver=Q)
  ~/lookup/getValues.perl --flat=$flat /fast/${t}Full$ver
else
 [[ -f /fast/${t}Full$ver.0.tch ]] || ([[ /fast/${t}FullQ.0.tch ]] && ver=Q)
 if [[ -f /fast/${t}Full$ver.0.tch ]] 
 then 
   ~/lookup/getValues.perl --flat=$flat /fast/${t}Full$ver
 else
  if [[ ${da3[$t]} == 1 && $h != da3.eecs.utk.edu ]]
   then ssh da3 ~/lookup/getValues $pass ${t}
   else
    if [[ ${da3[$t]} == 1 && $h == da3.eecs.utk.edu ]]
    then echo here /fast/${t}Full$ver; ~/lookup/getValues.perl --flat=$flat /fast/${t}Full$ver
    else [[ $h == da0.eecs.utk.edu ]] && ~/lookup/getValues.perl --flat=$flat /data/basemaps/${t}Full$ver
	     [[ $h != da0.eecs.utk.edu ]] && ssh da0 ~/lookup/getValues.perl --flat=$flat /data/basemaps/${t}Full$ver
    fi
   fi
 fi
fi
