#PBS -N QStg2NNN
#PBS -A ACF-UTK0011
#PBS -l feature=beacon
#PBS -l partition=beacon
#PBS -l nodes=1:ppn=16,walltime=23:50:00
#PBS -j oe
#PBS -S /bin/bash
ver=Q
#DT=201910.Otr
DT=201910
DT=201910.Stg2
sub=NNN
#c=/lustre/haven/user/audris/${ver}.Otr.$sub
c=/lustre/haven/user/audris/${ver}.$sub
c=/lustre/haven/user/audris/${ver}.Stg2.$sub
cd $c
/nics/b/home/audris/bin/doSkylakeUp1.sh $sub ${ver}1 $c $DT list New
 
