#!/bin/bash

h=$(hostname)
t=$1

off=${3:-0}
fmt=${2:-0}


if [[ $t != 'blob' && $t != 'tree' && $t != 'commit' && $t != 'tag' ]]
then echo "no type $t"
   exit
fi

if [[ $h == da5.eecs.utk.edu ]] 
then 
  ~/lookup/showCnt.perl $t $fmt 0
else
 if [[ $t == 'blob' ]]
 then
    if [[ $h == 'da4.eecs.utk.edu' ]]
    then ~/lookup/showCnt.perl $t $fmt 1
    else ~/lookup/showCnt.perl $t $fmt 1
    fi
 else
  if [[ $t == 'tree' ]]
  then
    off=1
    if [[ $h == 'da3.eecs.utk.edu' || $h == 'da4.eecs.utk.edu' ]] 
    then 
      ~/lookup/showCnt.perl $t $fmt $off
    else
      ssh -p443 da4 ~/lookup/showCnt.perl $t $fmt $off
    fi
  else # commit/'tdiff'/'tkns'  
    if [[ $t == 'tdiff' || $t == 'tkns' ]]
    then 
      off=1
      ssh da3 ~/lookup/showCnt.perl $t $fmt $off
    else  #commit
      if [[ $h == 'da4.eecs.utk.edu' ]]
      then ~/lookup/showCnt.perl $t $fmt
      else
        off=0
        ssh da4 ~/lookup/showCnt.perl $t $fmt $off
      fi
    fi
   fi
  fi
fi
